import { useEffect, useState } from 'react';
import api from '../../services/api';
import toast from 'react-hot-toast';
import { Edit, Trash2 } from 'lucide-react';

const ManageCourses = () => {
  const [courses, setCourses] = useState([]);
  const [teachers, setTeachers] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [editingCourse, setEditingCourse] = useState(null);
  const [form, setForm] = useState({ title: '', description: '', teacherEmail: '', category: 'ol', image: '' });
  const [timetable, setTimetable] = useState([]);
  const [imagePreview, setImagePreview] = useState('');

  useEffect(() => { fetchData(); }, []);
  const fetchData = async () => { try { const [cRes, tRes] = await Promise.all([api.get('/admin/courses'), api.get('/admin/teachers')]); setCourses(cRes.data.courses); setTeachers(tRes.data.teachers); } catch (err) { toast.error('Failed to load data'); } };
  const handleImageUpload = (e) => { const file = e.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onloadend = () => { setForm({ ...form, image: reader.result }); setImagePreview(reader.result); }; reader.readAsDataURL(file); };
  const createCourse = async (e) => { e.preventDefault(); try { await api.post('/admin/courses', form); toast.success('Course created'); setShowForm(false); setForm({ title: '', description: '', teacherEmail: '', category: 'ol', image: '' }); setImagePreview(''); fetchData(); } catch(err) { toast.error(err.response?.data?.message || 'Creation failed'); } };
  const updateCourse = async (e) => { e.preventDefault(); try { await api.put(`/admin/courses/${editingCourse._id}`, { ...form, timetable }); toast.success('Course updated'); setEditingCourse(null); fetchData(); } catch(err) { toast.error(err.response?.data?.message || 'Update failed'); } };
  const deleteCourse = async (id) => { if (confirm('Delete this course permanently?')) { try { await api.delete(`/admin/courses/${id}`); toast.success('Deleted'); fetchData(); } catch(err) { toast.error('Failed to delete'); } } };
  const openEditModal = (course) => { setEditingCourse(course); setForm({ title: course.title, description: course.description, teacherEmail: course.teacherEmail, category: course.category || 'ol', image: course.image || '' }); setImagePreview(course.image || ''); setTimetable(course.timetable || []); };
  const addTimeSlot = () => setTimetable([...timetable, { day: 'Monday', startTime: '09:00', endTime: '10:00' }]);
  const updateTimeSlot = (idx, field, value) => { const newTt = [...timetable]; newTt[idx][field] = value; setTimetable(newTt); };
  const removeTimeSlot = (idx) => setTimetable(timetable.filter((_, i) => i !== idx));
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

  return (
    <div className="min-h-screen py-20 px-6">
      <div className="container mx-auto">
        <div className="flex justify-between items-center mb-6"><h1 className="text-3xl font-bold">Manage Courses</h1><button onClick={() => setShowForm(!showForm)} className="btn-primary px-4 py-2 rounded-lg">+ New Course</button></div>
        {showForm && (<div className="glass-card p-6 mb-6"><form onSubmit={createCourse} className="space-y-4"><input type="text" placeholder="Title" required className="glass-input w-full" value={form.title} onChange={e => setForm({...form, title: e.target.value})} /><textarea placeholder="Description" required rows="3" className="glass-input w-full" value={form.description} onChange={e => setForm({...form, description: e.target.value})} /><select required className="glass-input w-full" value={form.teacherEmail} onChange={e => setForm({...form, teacherEmail: e.target.value})}><option value="">Assign Teacher</option>{teachers.map(t => <option key={t.email} value={t.email}>{t.name} ({t.email})</option>)}</select><select required className="glass-input w-full" value={form.category} onChange={e => setForm({...form, category: e.target.value})}><option value="ol">Ordinary Level (OL)</option><option value="al">Advanced Level (AL)</option></select><div><label className="block text-sm text-gray-300 mb-1">Course Image</label><input type="file" accept="image/*" onChange={handleImageUpload} className="glass-input w-full" />{imagePreview && <img src={imagePreview} alt="Preview" className="mt-2 h-32 object-cover rounded" />}</div><button type="submit" className="btn-primary w-full py-2 rounded-lg">Create Course</button></form></div>)}
        {editingCourse && (<div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4 overflow-y-auto"><div className="glass-card p-6 max-w-2xl w-full max-h-[90vh] overflow-y-auto"><h2 className="text-2xl font-bold mb-4">Edit Course</h2><form onSubmit={updateCourse} className="space-y-4"><input type="text" placeholder="Title" required className="glass-input w-full" value={form.title} onChange={e => setForm({...form, title: e.target.value})} /><textarea placeholder="Description" required rows="3" className="glass-input w-full" value={form.description} onChange={e => setForm({...form, description: e.target.value})} /><select required className="glass-input w-full" value={form.teacherEmail} onChange={e => setForm({...form, teacherEmail: e.target.value})}><option value="">Assign Teacher</option>{teachers.map(t => <option key={t.email} value={t.email}>{t.name} ({t.email})</option>)}</select><select required className="glass-input w-full" value={form.category} onChange={e => setForm({...form, category: e.target.value})}><option value="ol">Ordinary Level (OL)</option><option value="al">Advanced Level (AL)</option></select><div><label className="block text-sm text-gray-300 mb-1">Course Image</label><input type="file" accept="image/*" onChange={handleImageUpload} className="glass-input w-full" />{imagePreview && <img src={imagePreview} alt="Preview" className="mt-2 h-32 object-cover rounded" />}</div><div><label className="block text-sm font-semibold mb-2">Timetable</label>{timetable.map((slot, idx) => (<div key={idx} className="flex gap-2 mb-2"><select value={slot.day} onChange={e => updateTimeSlot(idx, 'day', e.target.value)} className="glass-input flex-1">{days.map(d => <option key={d}>{d}</option>)}</select><input type="time" value={slot.startTime} onChange={e => updateTimeSlot(idx, 'startTime', e.target.value)} className="glass-input w-28" /><input type="time" value={slot.endTime} onChange={e => updateTimeSlot(idx, 'endTime', e.target.value)} className="glass-input w-28" /><button type="button" onClick={() => removeTimeSlot(idx)} className="text-red-400">✖</button></div>))}<button type="button" onClick={addTimeSlot} className="text-purple-400 text-sm">+ Add Time Slot</button></div><div className="flex gap-3"><button type="submit" className="btn-primary px-6 py-2 rounded-lg">Save Changes</button><button type="button" onClick={() => setEditingCourse(null)} className="btn-secondary px-6 py-2 rounded-lg">Cancel</button></div></form></div></div>)}
        <div className="glass-card p-6">{courses.map(course => (<div key={course._id} className="flex justify-between items-center glass-card p-4 mb-2"><div className="flex gap-4 items-center">{course.image && <img src={course.image} alt={course.title} className="w-16 h-16 object-cover rounded" />}<div><h3 className="font-semibold">{course.title}</h3><p className="text-sm text-gray-400">Teacher: {course.teacherName} ({course.teacherEmail})</p><p className="text-xs text-purple-300">Category: {course.category === 'ol' ? 'OL' : 'AL'}</p></div></div><div className="flex gap-2"><button onClick={() => openEditModal(course)} className="text-blue-400 text-sm flex items-center gap-1"><Edit size={16} /> Edit</button><button onClick={() => deleteCourse(course._id)} className="text-red-400 text-sm flex items-center gap-1"><Trash2 size={16} /> Delete</button></div></div>))}</div>
      </div>
    </div>
  );
};
export default ManageCourses;